import setuptools

setuptools.setup(name='nanobot-plugin-splatoon2tools',  # 包名
      version='1.0.0',  # 版本号
      description='splatoon2 tools bot',
      long_description='splatoon2 tools bot',
      author='DrinkOolongTea',
      author_email='sh.elsyion@qq.com',
      url='https://github.com/DrinkOolongTea/splatong2-bot',
      install_requires=["lxml",
      "Pillow"],
      license='GNU General Public License v3.0',
      packages=setuptools.find_packages(),
      data_files=[('resource', ["splatoon2_tools/resource/.52_Gal.png"]),
('resource', ["splatoon2_tools/resource/.96_Gal.png"]),
('resource', ["splatoon2_tools/resource/Aerospray_MG.png"]),
('resource', ["splatoon2_tools/resource/Ancho-V_Games.png"]),
('resource', ["splatoon2_tools/resource/Arowana_Mall.png"]),
('resource', ["splatoon2_tools/resource/Ballpoint_Splatling.png"]),
('resource', ["splatoon2_tools/resource/Bamboozler_14_Mk_I.png"]),
('resource', ["splatoon2_tools/resource/Blackbelly_Skatepark.png"]),
('resource', ["splatoon2_tools/resource/Blaster.png"]),
('resource', ["splatoon2_tools/resource/Bloblobber.png"]),
('resource', ["splatoon2_tools/resource/Camp_Triggerfish.png"]),
('resource', ["splatoon2_tools/resource/Carbon_Roller.png"]),
('resource', ["splatoon2_tools/resource/china.TTF"]),
('resource', ["splatoon2_tools/resource/Clash_Blaster.png"]),
('resource', ["splatoon2_tools/resource/Classic_Squiffer.png"]),
('resource', ["splatoon2_tools/resource/Dapple_Dualies.png"]),
('resource', ["splatoon2_tools/resource/Dark_Tetra_Dualies.png"]),
('resource', ["splatoon2_tools/resource/Dualie_Squelchers.png"]),
('resource', ["splatoon2_tools/resource/Dual_Squelcher.png"]),
('resource', ["splatoon2_tools/resource/Dynamo_Roller.png"]),
('resource', ["splatoon2_tools/resource/E-liter_4K.png"]),
('resource', ["splatoon2_tools/resource/E-liter_4K_Scope.png"]),
('resource', ["splatoon2_tools/resource/Explosher.png"]),
('resource', ["splatoon2_tools/resource/Flingza_Roller.png"]),
('resource', ["splatoon2_tools/resource/Glooga_Dualies.png"]),
('resource', ["splatoon2_tools/resource/Goby_Arena.png"]),
('resource', ["splatoon2_tools/resource/Goo_Tuber.png"]),
('resource', ["splatoon2_tools/resource/H-3_Nozzlenose.png"]),
('resource', ["splatoon2_tools/resource/Heavy_Splatling.png"]),
('resource', ["splatoon2_tools/resource/Humpback_Pump_Track.png"]),
('resource', ["splatoon2_tools/resource/Hydra_Splatling.png"]),
('resource', ["splatoon2_tools/resource/Inkblot_Art_Academy.png"]),
('resource', ["splatoon2_tools/resource/Inkbrush.png"]),
('resource', ["splatoon2_tools/resource/Jet_Squelcher.png"]),
('resource', ["splatoon2_tools/resource/Kelp_Dome.png"]),
('resource', ["splatoon2_tools/resource/L-3_Nozzlenose.png"]),
('resource', ["splatoon2_tools/resource/league_battle.png"]),
('resource', ["splatoon2_tools/resource/Lost_Outpost.png"]),
('resource', ["splatoon2_tools/resource/Luna_Blaster.png"]),
('resource', ["splatoon2_tools/resource/MakoMart.png"]),
('resource', ["splatoon2_tools/resource/Manta_Maria.png"]),
('resource', ["splatoon2_tools/resource/Marooner's_Bay.png"]),
('resource', ["splatoon2_tools/resource/Mini_Splatling.png"]),
('resource', ["splatoon2_tools/resource/Moray_Towers.png"]),
('resource', ["splatoon2_tools/resource/Musselforge_Fitness.png"]),
('resource', ["splatoon2_tools/resource/N-ZAP_'85.png"]),
('resource', ["splatoon2_tools/resource/Nautilus_47.png"]),
('resource', ["splatoon2_tools/resource/New_Albacore_Hotel.png"]),
('resource', ["splatoon2_tools/resource/Octobrush.png"]),
('resource', ["splatoon2_tools/resource/Piranha_Pit.png"]),
('resource', ["splatoon2_tools/resource/Port_Mackerel.png"]),
('resource', ["splatoon2_tools/resource/Random.png"]),
('resource', ["splatoon2_tools/resource/Random_2.png"]),
('resource', ["splatoon2_tools/resource/Range_Blaster.png"]),
('resource', ["splatoon2_tools/resource/ranked_battle.png"]),
('resource', ["splatoon2_tools/resource/Rapid_Blaster.png"]),
('resource', ["splatoon2_tools/resource/Rapid_Blaster_Pro.png"]),
('resource', ["splatoon2_tools/resource/regular_battle.png"]),
('resource', ["splatoon2_tools/resource/Ruins_of_Ark_Polaris.png"]),
('resource', ["splatoon2_tools/resource/Salmonid_Smokeyard.png"]),
('resource', ["splatoon2_tools/resource/salmon_run.png"]),
('resource', ["splatoon2_tools/resource/Shellendorf_Institute.png"]),
('resource', ["splatoon2_tools/resource/Shifty_Station.png"]),
('resource', ["splatoon2_tools/resource/Skipper_Pavilion.png"]),
('resource', ["splatoon2_tools/resource/Slosher.png"]),
('resource', ["splatoon2_tools/resource/Sloshing_Machine.png"]),
('resource', ["splatoon2_tools/resource/Snapper_Canal.png"]),
('resource', ["splatoon2_tools/resource/Spawning_Grounds.png"]),
('resource', ["splatoon2_tools/resource/Splash-o-matic.png"]),
('resource', ["splatoon2_tools/resource/Splatterscope.png"]),
('resource', ["splatoon2_tools/resource/Splattershot.png"]),
('resource', ["splatoon2_tools/resource/Splattershot_Jr.png"]),
('resource', ["splatoon2_tools/resource/Splattershot_Pro.png"]),
('resource', ["splatoon2_tools/resource/Splat_Brella.png"]),
('resource', ["splatoon2_tools/resource/Splat_Charger.png"]),
('resource', ["splatoon2_tools/resource/Splat_Dualies.png"]),
('resource', ["splatoon2_tools/resource/Splat_Roller.png"]),
('resource', ["splatoon2_tools/resource/Sploosh-o-matic.png"]),
('resource', ["splatoon2_tools/resource/Squeezer.png"]),
('resource', ["splatoon2_tools/resource/Starfish_Mainstage.png"]),
('resource', ["splatoon2_tools/resource/Sturgeon_Shipyard.png"]),
('resource', ["splatoon2_tools/resource/Tenta_Brella.png"]),
('resource', ["splatoon2_tools/resource/The_Reef.png"]),
('resource', ["splatoon2_tools/resource/tmp.png"]),
('resource', ["splatoon2_tools/resource/tmp1.png"]),
('resource', ["splatoon2_tools/resource/Tri-Slosher.png"]),
('resource', ["splatoon2_tools/resource/Undercover_Brella.png"]),
('resource', ["splatoon2_tools/resource/Wahoo_World.png"]),
('resource', ["splatoon2_tools/resource/Walleye_Warehouse.png"]),
('resource', ["splatoon2_tools/resource/ypifounts.TTF"])],
      classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
        "Operating System :: OS Independent",
      ],
      )
